project:
  type: website

website:
  title: "Portfólio"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
      - text: "Currículo"
        href: curriculo-matheus-kochaki.html
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

